services:
  wedding-site:
    build:
      context: .
      dockerfile: Dockerfile
    image: wedding-invite:latest
    container_name: wedding-invite
    restart: unless-stopped
    env_file:
      - .env.deploy
    ports:
      - "127.0.0.1:8081:80"
